services:
  - type: web
    name: amanklik-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        value: amanklik-secret-key-2026-vibe-coding
      - key: GOOGLE_CLIENT_ID
        value: 575126371408-24cf56dvn0m8gih1ieip7shrk3s2so17.apps.googleusercontent.com
      - key: CORS_ORIGIN
        sync: false
